Repository cognizance-amrita/cognizance_cms, pull requests merged in 2021-03, with the labels that each got.

#22 Added automatic member creation on acceptance of applications
  adminapp/views.py
Labels: enhancement

#24 Added bot access
  adminapp/__pycache__/__init__.cpython-38.pyc
  adminapp/__pycache__/admin.cpython-38.pyc
  adminapp/__pycache__/announcer.cpython-38.pyc
  adminapp/__pycache__/daterange.cpython-38.pyc
  adminapp/__pycache__/decorators.cpython-38.pyc
  adminapp/__pycache__/models.cpython-38.pyc
  adminapp/__pycache__/status_update.cpython-38.pyc
  adminapp/__pycache__/urls.cpython-38.pyc
  adminapp/__pycache__/views.cpython-38.pyc
  adminapp/bot.py
  adminapp/migrations/__pycache__/0001_initial.cpython-38.pyc
  adminapp/migrations/__pycache__/0002_auto_20210111_1520.cpython-38.pyc
  adminapp/migrations/__pycache__/0003_achievement_meeting_statusupdate_streakcount_submission_task.cpython-38.pyc
  adminapp/migrations/__pycache__/0004_auto_20210111_1812.cpython-38.pyc
  adminapp/migrations/__pycache__/0005_auto_20210121_2042.cpython-38.pyc
  adminapp/migrations/__pycache__/0006_auto_20210121_2043.cpython-38.pyc
  adminapp/migrations/__pycache__/0007_auto_20210121_2043.cpython-38.pyc
  adminapp/migrations/__pycache__/0008_streakcount.cpython-38.pyc
  adminapp/migrations/__pycache__/0009_achievement.cpython-38.pyc
  adminapp/migrations/__pycache__/0010_task.cpython-38.pyc
  adminapp/migrations/__pycache__/0011_submission.cpython-38.pyc
  adminapp/migrations/__pycache__/0012_meeting_statusupdate.cpython-38.pyc
  adminapp/migrations/__pycache__/0013_auto_20210123_1525.cpython-38.pyc
  adminapp/migrations/__pycache__/0014_auto_20210123_1535.cpython-38.pyc
  adminapp/migrations/__pycache__/0015_auto_20210201_1933.cpython-38.pyc
  adminapp/migrations/__pycache__/__init__.cpython-38.pyc
  adminapp/views.py
  cognizance_cms/__pycache__/__init__.cpython-38.pyc
  cognizance_cms/__pycache__/settings.cpython-38.pyc
  cognizance_cms/__pycache__/urls.cpython-38.pyc
  cognizance_cms/__pycache__/wsgi.cpython-38.pyc
  membersapp/__pycache__/__init__.cpython-38.pyc
  membersapp/__pycache__/admin.cpython-38.pyc
  membersapp/__pycache__/decorators.cpython-38.pyc
  membersapp/__pycache__/models.cpython-38.pyc
  membersapp/__pycache__/urls.cpython-38.pyc
  membersapp/__pycache__/views.cpython-38.pyc
  pages/__pycache__/__init__.cpython-38.pyc
  pages/__pycache__/admin.cpython-38.pyc
  pages/__pycache__/decorators.cpython-38.pyc
  pages/__pycache__/models.cpython-38.pyc
  pages/__pycache__/urls.cpython-38.pyc
  pages/__pycache__/views.cpython-38.pyc
  pages/migrations/__pycache__/0001_initial.cpython-38.pyc
  pages/migrations/__pycache__/0002_auto_20210111_1812.cpython-38.pyc
  pages/migrations/__pycache__/0003_auto_20210121_2042.cpython-38.pyc
  pages/migrations/__pycache__/0004_application_displayusernames.cpython-38.pyc
  pages/migrations/__pycache__/0005_auto_20210201_1933.cpython-38.pyc
  pages/migrations/__pycache__/__init__.cpython-38.pyc
Labels: enhancement

#25 Fixed a major security issue
  pages/templates/pages/achievements.html
Labels: bug

#32 Favicon added to the site + Copyright year changed
  adminapp/templates/adminapp/accepted-mail-template.html
  adminapp/templates/adminapp/add-group.html
  adminapp/templates/adminapp/add-meeting.html
  adminapp/templates/adminapp/add-members.html
  adminapp/templates/adminapp/admin-applications.html
  adminapp/templates/adminapp/admin-dashboard.html
  adminapp/templates/adminapp/admin-groups.html
  adminapp/templates/adminapp/admin-meetings.html
  adminapp/templates/adminapp/admin-members.html
  adminapp/templates/adminapp/admin-reviewing.html
  adminapp/templates/adminapp/admin-tasks.html
  adminapp/templates/adminapp/announcements.html
  adminapp/templates/adminapp/edit-profile.html
  adminapp/templates/adminapp/rejected-mail-template.html
  adminapp/templates/adminapp/status-update-template.html
  adminapp/templates/adminapp/status-updates.html
  adminapp/templates/adminapp/task-submissions.html
  cognizance_cms/static/img/favicon.ico
  membersapp/templates/membersapp/member-dashboard.html
  membersapp/templates/membersapp/member-tasks.html
  membersapp/templates/membersapp/submit-task.html
  pages/templates/pages/achievements.html
  pages/templates/pages/applications.html
  pages/templates/pages/apply.html
  pages/templates/pages/contact-us.html
  pages/templates/pages/gallery.html
  pages/templates/pages/index.html
  pages/templates/pages/login.html
  pages/templates/pages/member.html
  static/image/favicon.ico
Labels: enhancement, good first issue

#36 Edit Page - Admin App (Working State) 👍🏽
  adminapp/templates/adminapp/add-members.html
  adminapp/templates/adminapp/edit-profile.html
  adminapp/views.py
Labels: enhancement, good first issue

#49 Updated the SMTP auth password
  adminapp/__pycache__/views.cpython-38.pyc
  adminapp/bot.py
  cognizance_cms/settings.py
Labels: bug

#50 Added GraphiQL interfacing
  adminapp/__pycache__/__init__.cpython-38.pyc
  adminapp/__pycache__/admin.cpython-38.pyc
  adminapp/__pycache__/announcer.cpython-38.pyc
  adminapp/__pycache__/daterange.cpython-38.pyc
  adminapp/__pycache__/decorators.cpython-38.pyc
  adminapp/__pycache__/models.cpython-38.pyc
  adminapp/__pycache__/status_update.cpython-38.pyc
  adminapp/__pycache__/urls.cpython-38.pyc
  adminapp/api/schema.py
  adminapp/migrations/__pycache__/0001_initial.cpython-38.pyc
  adminapp/migrations/__pycache__/0002_auto_20210111_1520.cpython-38.pyc
  adminapp/migrations/__pycache__/0003_achievement_meeting_statusupdate_streakcount_submission_task.cpython-38.pyc
  adminapp/migrations/__pycache__/0004_auto_20210111_1812.cpython-38.pyc
  adminapp/migrations/__pycache__/0005_auto_20210121_2042.cpython-38.pyc
  adminapp/migrations/__pycache__/0006_auto_20210121_2043.cpython-38.pyc
  adminapp/migrations/__pycache__/0007_auto_20210121_2043.cpython-38.pyc
  adminapp/migrations/__pycache__/0008_streakcount.cpython-38.pyc
  adminapp/migrations/__pycache__/0009_achievement.cpython-38.pyc
  adminapp/migrations/__pycache__/0010_task.cpython-38.pyc
  adminapp/migrations/__pycache__/0011_submission.cpython-38.pyc
  adminapp/migrations/__pycache__/0012_meeting_statusupdate.cpython-38.pyc
  adminapp/migrations/__pycache__/0013_auto_20210123_1525.cpython-38.pyc
  adminapp/migrations/__pycache__/0014_auto_20210123_1535.cpython-38.pyc
  adminapp/migrations/__pycache__/0015_auto_20210201_1933.cpython-38.pyc
  adminapp/migrations/__pycache__/__init__.cpython-38.pyc
  cognizance_cms/__pycache__/__init__.cpython-38.pyc
  cognizance_cms/__pycache__/settings.cpython-38.pyc
  cognizance_cms/__pycache__/urls.cpython-38.pyc
  cognizance_cms/__pycache__/wsgi.cpython-38.pyc
  cognizance_cms/api/schema.py
  cognizance_cms/settings.py
  cognizance_cms/urls.py
  membersapp/__pycache__/__init__.cpython-38.pyc
  membersapp/__pycache__/admin.cpython-38.pyc
  membersapp/__pycache__/decorators.cpython-38.pyc
  membersapp/__pycache__/models.cpython-38.pyc
  membersapp/__pycache__/urls.cpython-38.pyc
  membersapp/__pycache__/views.cpython-38.pyc
  pages/__pycache__/__init__.cpython-38.pyc
  pages/__pycache__/admin.cpython-38.pyc
  pages/__pycache__/decorators.cpython-38.pyc
  pages/__pycache__/models.cpython-38.pyc
  pages/__pycache__/urls.cpython-38.pyc
  pages/__pycache__/views.cpython-38.pyc
  pages/migrations/__pycache__/0001_initial.cpython-38.pyc
  pages/migrations/__pycache__/0002_auto_20210111_1812.cpython-38.pyc
  pages/migrations/__pycache__/0003_auto_20210121_2042.cpython-38.pyc
  pages/migrations/__pycache__/0004_application_displayusernames.cpython-38.pyc
  pages/migrations/__pycache__/0005_auto_20210201_1933.cpython-38.pyc
  pages/migrations/__pycache__/__init__.cpython-38.pyc
  requirements.txt
Labels: enhancement

#56 Added periodic status update mailer
  Dockerfile
  adminapp/cron.py
  cognizance_cms/__pycache__/settings.cpython-38.pyc
  cognizance_cms/settings.py
Labels: bug

#71 Updated Logo with size 32x32
  cognizance_cms/static/img/favicon.ico
  static/image/favicon.ico
Labels: enhancement

#84 Fixed the path ambiguity error
  adminapp/decorators.py
  adminapp/urls.py
Labels: bug
